apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crawler-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/$2
spec:
  rules:
    - host: api.crawler.local
      http:
        paths:
          - path: /discovery(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: url-discovery
                port:
                  number: 8081
          - path: /processor(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: processor
                port:
                  number: 8083
