spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8085
sensor:
  jitter:
    min: 100
    max: 300
  fail-rate: 0.25
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
sensor:
  jitter:
    min: ${SENSOR_JITTER_MIN:100}
    max: ${SENSOR_JITTER_MAX:300}
  fail-rate: ${SENSOR_FAIL_RATE:0.25}
